{% set name = "easyocr" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jaidedai/easyocr/archive/v{{ version }}.tar.gz
  sha256: 1c20356483964c7c80ccf86f2a0957cfed47768e9bbc99b9ff2eb47cb9cb1448
  patches:
    - fix-deps.patch

build:
  noarch: python
  entry_points:
    - easyocr= easyocr.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch
    - torchvision >=0.5
    - py-opencv
    - scipy
    - numpy
    - pillow
    - scikit-image
    - python-bidi
    - pyyaml
    - shapely
    - pyclipper
    - ninja

test:
  requires:
    - python {{ python_min }}
    - pip
    # https://github.com/conda-forge/opencv-feedstock/issues/400#issuecomment-2009561076
    - libopencv *=headless*  # [linux]
  imports:
    - easyocr
  commands:
    - pip check
    - easyocr --help

about:
  home: https://www.jaided.ai/
  dev_url: https://github.com/jaidedai/easyocr
  doc_url: https://www.jaided.ai/easyocr/documentation/
  license: Apache-2.0
  license_file: LICENSE
  summary: Ready-to-use OCR with 80+ supported languages and popular writing scripts.

extra:
  recipe-maintainers:
    - thewchan
