{% set name = "easyocr" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jaidedai/easyocr/archive/v{{ version }}.tar.gz
  sha256: 0ed5af2b739ce2303c5173d520b631df311d54a9aa58a80e09fe33d44c0a8115

build:
  skip: true  # [win]
  entry_points:
    - easyocr= easyocr.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - pip
    - python
  run:
    - ninja
    - numpy
    - pillow
    - python-bidi
    - py-opencv
    - pyclipper
    - python
    - pytorch
    - pyyaml
    - scikit-image
    - scipy
    - shapely
    - torchvision >=0.5

test:
  imports:
    - easyocr
  commands:
    - easyocr --help

about:
  home: https://www.jaided.ai/
  dev_url: https://github.com/jaidedai/easyocr
  doc_url: https://www.jaided.ai/easyocr/documentation/
  license: Apache-2.0
  license_file: LICENSE
  summary: Ready-to-use OCR with 80+ supported languages and popular writing scripts.

extra:
  recipe-maintainers:
    - thewchan
